heat_template_version: 2016-10-14

parameters:
  external_network:
    type: string
    description: Name of the external network
    default: ext-net-154

resources:
  private_net1:
    # sieťové prostredie
    type: OS::Neutron::Net
    properties:
      name: private-net1

  private_subnet1:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net1 }
      cidr: 192.168.10.0/24
      ip_version: 4
      gateway_ip: 192.168.10.1

  private_net2:
    type: OS::Neutron::Net
    properties:
      name: private-net2

  private_subnet2:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net2 }
      cidr: 192.168.20.0/24
      ip_version: 4
      gateway_ip: 192.168.20.1

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: external_network }

  router_interface1:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet1 }

  router_interface2:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet2 }
    
  server1:
    # vytváranie a management VM
    type: OS::Nova::Server
    properties:
      name: server1
      availability_zone: nova
      flavor: 1c05r8d
      image: debian-12-kis
      networks:
        - network: { get_resource: private_net1 }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            apt-get update
            apt-get upgrade -y
            apt-get install -y mc
          params: {}

  server2:
    type: OS::Nova::Server
    properties:
      name: server2
      availability_zone: nova
      flavor: 1c05r8d
      image: debian-12-kis
      networks:
        - network: { get_resource: private_net2 }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            apt-get update
            apt-get upgrade -y
            apt-get install -y mc
          params: {}
